name: PHP Linting
on:
  pull_request:
    paths:
      - "**/*.php"
      - "pint.json"
      - ".github/workflows/pint.yml"
      - "composer.json"
      - "composer.lock"
jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@2.3.1
        with:
          verboseMode: true
          testMode: true
